### ISSUE TITLE
Implement losing functionality. Add map specific losing criteria to json file. Like n_collisions, max_time etc

### ISSUE THREAD

**Issue by pritam-dey3** [Anand1310/summer-code-jam-2021#49]
We can also rewrite each levels in `levels.py`. Adding level specific losing criteria in `__init__`.

Currently `Level` class loads the maze with `Maze.load()`. We can clone this class to create `Level2`, `Level3` and just add some code in proper places to detect loss.

**Comment by Anand1310** [comment]
Done
