### ISSUE TITLE
Load dialogues from json files

### ISSUE THREAD

**Issue by pritam-dey3** [Anand1310/summer-code-jam-2021#59]
Dialogues are stored in the json file in the following way:

```json
{
    "dialogues": [ [ [6,0], [4,2], "This is a box. You know what to do ;)"],
                   [ [6,18], [-3,16], "Oops, I think you are trapped. Fortunately you have echo location"]]
}
```
This says that when player reaches location (in matrix) (6,0), the text "This is a box. You know what to do ;)" appears in (4,2) (matrix location) and so on.

* First dialogue should be shown in `if start_frame == True:` block. (assuming (6,0) is starting location)
* For all the dialogues after that we need to store the hit-points (moving cursor to this place makes corresponding dialogue appear), and check whether user is currently in any of those points. In `if val.is_sequence:` block.
* Show the dialogue. (? Remove the dialogue)
* Remove the location from hit-points list.
* You can start on the branch `level_design` from [here](https://github.com/Anand1310/summer-code-jam-2021/issues/59#issue-946232472).

**Comment by Anand1310** [comment]
Done
